# site properties and page defaults
title: Thin Ice [DRAFT]
subtitle: # TODO Should be added?
description: Researching how changes to ice cover impact phytoplankton structure and function # TODO Should be updated?
header: images/background.jpg # TODO Needs to be updated
footer: images/background.jpg # TODO Needs to be updated
proofer: false # STODO hould be enabled after deleting some of the default files

# site social media and other links
links:
  github: NSFThinIce

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
